# -*- coding: utf-8 -*-
"""Copy of thesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJRbBdGhEyEpUEBaF_PeEQ-2FNHejd1X
"""

import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import seaborn as sns
from tqdm import tqdm
from collections import Counter
import hashlib
import random

# Reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)

from google.colab import files
uploaded = files.upload()  # choose your ZIP file from your PC

import zipfile

with zipfile.ZipFile("archive.zip", "r") as zip_ref:
# change filename to cifake and extract
  zip_ref.extractall("CIFAKE")

# ✅ 1. Define dataset paths
train_dir = "/content/CIFAKE/train"
test_dir  = "/content/CIFAKE/test"

# ✅ 2. count images
real_train = len(os.listdir(os.path.join(train_dir, "REAL")))
fake_train = len(os.listdir(os.path.join(train_dir, "FAKE")))
real_test  = len(os.listdir(os.path.join(test_dir,  "REAL")))
fake_test  = len(os.listdir(os.path.join(test_dir,  "FAKE")))

# ✅ 3. Print summary
print(f"Train: REAL = {real_train}, FAKE = {fake_train}")
print(f"Test : REAL = {real_test},  FAKE = {fake_test}")

DATASET_DIR = "/content/CIFAKE"
SPLITS = ["train", "test"]
CLASSES = ["REAL", "FAKE"]

image_paths = []
labels = []
splits = []

for split in SPLITS:
    for label in CLASSES:
        class_dir = os.path.join(DATASET_DIR, split, label)
        for file in os.listdir(class_dir):
            image_paths.append(os.path.join(class_dir, file))
            labels.append(label)
            splits.append(split)

df = pd.DataFrame({
    "path": image_paths,
    "label": labels,
    "split": splits
})

print(df["label"].value_counts())
print(df["split"].value_counts())

#Dataset Integrity Check (Corrupted Images)
valid_images = []
invalid_images = []

for path in tqdm(df["path"]):
    try:
        img = cv2.imread(path)
        if img is None or img.size == 0:
            invalid_images.append(path)
        else:
            valid_images.append(path)
    except:
        invalid_images.append(path)

print(f"Valid images: {len(valid_images)}")
print(f"Corrupted images: {len(invalid_images)}")

df = df[df["path"].isin(valid_images)].reset_index(drop=True)

class_counts = df["label"].value_counts()

plt.figure(figsize=(5,4))
class_counts.plot(kind="bar")
plt.title("Class Distribution")
plt.ylabel("Number of Images")
plt.xticks(rotation=0)
plt.show()

print((class_counts / len(df)) * 100)

import os
import shutil
import random

# ---------------------------
# Reproducibility
# ---------------------------
SEED = 42
random.seed(SEED)

# ---------------------------
# Paths
# ---------------------------
base_dir = "/content/CIFAKE"
train_dir = os.path.join(base_dir, "train")
test_dir = os.path.join(base_dir, "test")
output_dir = "/content/CIFAKE_split"

classes = ["REAL", "FAKE"]
splits = ["train", "val", "test"]

# ---------------------------
# Create output directories
# ---------------------------
for split in splits:
    for cls in classes:
        os.makedirs(os.path.join(output_dir, split, cls), exist_ok=True)

# ---------------------------
# Copy test set (20k images)
# ---------------------------
for cls in classes:
    test_src = os.path.join(test_dir, cls)
    test_dst = os.path.join(output_dir, "test", cls)

    test_images = [
        f for f in os.listdir(test_src)
        if f.lower().endswith(('.jpg', '.jpeg', '.png'))
    ]

    for img in test_images:
        shutil.copy(
            os.path.join(test_src, img),
            os.path.join(test_dst, img)
        )

# ---------------------------
# Split train into 90k train + 10k val
# ---------------------------
for cls in classes:
    img_dir = os.path.join(train_dir, cls)

    images = [
        f for f in os.listdir(img_dir)
        if f.lower().endswith(('.jpg', '.jpeg', '.png'))
    ]

    random.shuffle(images)

    total = len(images)
    val_count = int(0.1 * total)   # 10% for validation

    val_imgs = images[:val_count]
    train_imgs = images[val_count:]

    for img in train_imgs:
        shutil.copy(
            os.path.join(img_dir, img),
            os.path.join(output_dir, "train", cls, img)
        )

    for img in val_imgs:
        shutil.copy(
            os.path.join(img_dir, img),
            os.path.join(output_dir, "val", cls, img)
        )

# ---------------------------
# Final confirmation
# ---------------------------
print("✅ CIFAKE dataset successfully split into:")
print("   • 90,000 training images")
print("   • 10,000 validation images")
print("   • 20,000 test images")
print("   • Random seed fixed for reproducibility")

for split in ["train", "val", "test"]:
    count = 0
    for cls in classes:
        count += len(os.listdir(os.path.join(output_dir, split, cls)))
    print(f"{split.upper()} images: {count}")

import os
import pandas as pd
import matplotlib.pyplot as plt

# ---------------------------
# Dataset directories
# ---------------------------
base_dir = "/content/CIFAKE_split"
train_dir = os.path.join(base_dir, "train")
val_dir   = os.path.join(base_dir, "val")
test_dir  = os.path.join(base_dir, "test")

# ---------------------------
# Count images per class
# ---------------------------
real_train = len(os.listdir(os.path.join(train_dir, "REAL")))
fake_train = len(os.listdir(os.path.join(train_dir, "FAKE")))

real_validation = len(os.listdir(os.path.join(val_dir, "REAL")))
fake_validation = len(os.listdir(os.path.join(val_dir, "FAKE")))

real_test = len(os.listdir(os.path.join(test_dir, "REAL")))
fake_test = len(os.listdir(os.path.join(test_dir, "FAKE")))

# ---------------------------
# Summary table
# ---------------------------
data_summary = pd.DataFrame({
    "Dataset": ["Train", "Validation", "Test"],
    "Real": [real_train, real_validation, real_test],
    "Fake": [fake_train, fake_validation, fake_test]
})

# ---------------------------
# Plot
# ---------------------------
data_summary.set_index("Dataset").plot(
    kind="bar",
    stacked=True,
    figsize=(7,5)
)

plt.title("Class Distribution: Real vs Fake Images")
plt.ylabel("Number of Images")
plt.xlabel("Dataset Split")
plt.tight_layout()
plt.show()

# Combine all counts and show through pie chart
counts = [real_train, fake_train, real_validation, fake_validation, real_test, fake_test]
# Recompute counts from final split directories (DO NOT reuse old values)
real_train = len(os.listdir("/content/CIFAKE_split/train/REAL"))
fake_train = len(os.listdir("/content/CIFAKE_split/train/FAKE"))

real_validation = len(os.listdir("/content/CIFAKE_split/val/REAL"))
fake_validation = len(os.listdir("/content/CIFAKE_split/val/FAKE"))

real_test = len(os.listdir("/content/CIFAKE_split/test/REAL"))
fake_test = len(os.listdir("/content/CIFAKE_split/test/FAKE"))

labels = [
    f"REAL (Train)\n{real_train}",
    f"FAKE (Train)\n{fake_train}",
    f"REAL (Validation)\n{real_validation}",
    f"FAKE (Validation)\n{fake_validation}",
    f"REAL (Test)\n{real_test}",
    f"FAKE (Test)\n{fake_test}"
]

colors = ['#66b3ff', '#ff9999', '#99ff99', '#ffcc99', '#c2c2f0', '#ffb3e6']

def make_autopct(values):
    def my_autopct(pct):
        total = sum(values)
        count = int(round(pct * total / 100.0))
        return f'{count}\n({pct:.1f}%)'
    return my_autopct

plt.figure(figsize=(7,7))
plt.pie(
    counts,
    labels=labels,
    autopct=make_autopct(counts),
    startangle=90,
    colors=colors,
    shadow=True,
    textprops={'fontsize': 11}
)
plt.title("Train vs Validation vs Test (REAL & FAKE)", fontsize=14, fontweight='bold')
plt.show()

widths, heights, ratios = [], [], []

for path in tqdm(df["path"]):
    img = cv2.imread(path)
    h, w = img.shape[:2]
    widths.append(w)
    heights.append(h)
    ratios.append(w / h)

plt.figure(figsize=(6,4))
plt.hist(widths, bins=30, alpha=0.7, label="Width")
plt.hist(heights, bins=30, alpha=0.7, label="Height")
plt.legend()
plt.title("Image Resolution Distribution")
plt.show()

plt.figure(figsize=(6,4))
plt.hist(ratios, bins=30)
plt.title("Aspect Ratio Distribution")
plt.show()

# Sample Visualization per Class
def show_samples(label, n=10):
    paths = df[df["label"] == label]["path"].sample(n)
    plt.figure(figsize=(10,2))
    for i, p in enumerate(paths):
        img = cv2.cvtColor(cv2.imread(p), cv2.COLOR_BGR2RGB)
        plt.subplot(1, n, i+1)
        plt.imshow(img)
        plt.axis("off")
    plt.suptitle(f"Sample Images - {label}")
    plt.show()

show_samples("REAL")
show_samples("FAKE")

# Intensity & Contrast Analysis
intensity = []
contrast = []

for path in tqdm(df["path"]):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    intensity.append(np.mean(img))
    contrast.append(np.std(img))

plt.figure(figsize=(6,4))
plt.hist(intensity, bins=30)
plt.title("Mean Intensity Distribution")
plt.show()

plt.figure(figsize=(6,4))
plt.hist(contrast, bins=30)
plt.title("Contrast Distribution")
plt.show()

# Blur Detection (Laplacian Variance)
def blur_score(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    return cv2.Laplacian(gray, cv2.CV_64F).var()

blur_scores = []

for path in tqdm(df["path"]):
    img = cv2.imread(path)
    blur_scores.append(blur_score(img))

df["blur_score"] = blur_scores

plt.figure(figsize=(6,4))
plt.hist(df[df["label"]=="REAL"]["blur_score"], alpha=0.6, label="REAL")
plt.hist(df[df["label"]=="FAKE"]["blur_score"], alpha=0.6, label="FAKE")
plt.legend()
plt.title("Blur Score Distribution")
plt.show()

# Duplicate Image Detection (Hash-Based)
def image_hash(path):
    with open(path, "rb") as f:
        return hashlib.md5(f.read()).hexdigest()

hashes = {}
duplicates = []

for path in tqdm(df["path"]):
    h = image_hash(path)
    if h in hashes:
        duplicates.append(path)
    else:
        hashes[h] = path

print(f"Duplicate images found: {len(duplicates)}")

# Preprocessing Pipeline (Resize + Normalize)
TARGET_SIZE = (224, 224)

def preprocess_image(path):
    img = cv2.imread(path)
    img = cv2.resize(img, TARGET_SIZE)
    img = img.astype(np.float32) / 255.0
    return img

# Blur Handling Policy
BLUR_THRESHOLD = 100.0

blurry_images = df[df["blur_score"] < BLUR_THRESHOLD]
print(f"Blurry images detected: {len(blurry_images)}")

# Option: keep but flag (recommended)
df["is_blurry"] = df["blur_score"] < BLUR_THRESHOLD

sample_path = df.iloc[0]["path"]

orig = cv2.cvtColor(cv2.imread(sample_path), cv2.COLOR_BGR2RGB)
proc = preprocess_image(sample_path)

plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(orig)
plt.title("Original")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(proc)
plt.title("Preprocessed")
plt.axis("off")
plt.show()

print("Processed shape:", proc.shape)
print("Pixel range:", proc.min(), proc.max())

#Pixel Value Distribution
def get_mean_intensity(folder, n=300):
    means = []
    img_list = os.listdir(folder)
    if len(img_list) < n:
        n = len(img_list)
    for img_name in random.sample(img_list, n):
        img = np.array(Image.open(os.path.join(folder, img_name)).convert("RGB"))
        means.append(img.mean())
    return means

# Train
real_train_means = get_mean_intensity(os.path.join(train_dir, "REAL"))
fake_train_means = get_mean_intensity(os.path.join(train_dir, "FAKE"))

# Validation
real_val_means = get_mean_intensity(os.path.join(val_dir, "REAL"))
fake_val_means = get_mean_intensity(os.path.join(val_dir, "FAKE"))

# Test
real_test_means = get_mean_intensity(os.path.join(test_dir, "REAL"))
fake_test_means = get_mean_intensity(os.path.join(test_dir, "FAKE"))
# Plot histograms
plt.figure(figsize=(10,5))
plt.hist(real_train_means, bins=30, alpha=0.6, label='Train REAL')
plt.hist(fake_train_means, bins=30, alpha=0.6, label='Train FAKE')
plt.hist(real_val_means, bins=30, alpha=0.4, label='Val REAL')
plt.hist(fake_val_means, bins=30, alpha=0.4, label='Val FAKE')
plt.hist(real_test_means, bins=30, alpha=0.2, label='Test REAL')
plt.hist(fake_test_means, bins=30, alpha=0.2, label='Test FAKE')
plt.xlabel("Mean Pixel Intensity")
plt.ylabel("Frequency")
plt.title("Pixel Intensity Distribution (REAL vs FAKE, Train/Val/Test)")
plt.legend()
plt.show()

import tensorflow as tf

print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices('GPU'))

!nvidia-smi

from tensorflow.keras import mixed_precision

mixed_precision.set_global_policy('mixed_float16')

DATASET_PATH = "/content/CIFAKE_split"

train_dir = f"{DATASET_PATH}/train"
val_dir = f"{DATASET_PATH}/val"
test_dir = f"{DATASET_PATH}/test"

IMG_SIZE = 224
BATCH_SIZE = 64

# data Pipeline (map + prefetch)
AUTOTUNE = tf.data.AUTOTUNE

train_ds = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    label_mode="binary"
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    val_dir,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    label_mode="binary"
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    test_dir,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    label_mode="binary",
    shuffle=False
)

# Apply EfficientNet Preprocessing
from tensorflow.keras.applications.efficientnet import preprocess_input

def preprocess(images, labels):
    images = preprocess_input(images)
    return images, labels

train_ds = train_ds.map(preprocess, num_parallel_calls=AUTOTUNE)
val_ds = val_ds.map(preprocess, num_parallel_calls=AUTOTUNE)
test_ds = test_ds.map(preprocess, num_parallel_calls=AUTOTUNE)

train_ds = train_ds.prefetch(AUTOTUNE)
val_ds = val_ds.prefetch(AUTOTUNE)
test_ds = test_ds.prefetch(AUTOTUNE)

# Build EfficientNet Model
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

base_model = EfficientNetB0(
    weights="imagenet",
    include_top=False,
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

base_model.trainable = False  # Stage 1 freeze

x = GlobalAveragePooling2D()(base_model.output)
x = Dropout(0.4)(x)

output = Dense(1, activation="sigmoid", dtype="float32")(x)

model = Model(base_model.input, output)

# Compile Stage 1
model.compile(
    optimizer=Adam(1e-4),
    loss="binary_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.AUC(name="auc"),
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

# Train Stage 1 (Frozen Base)
history1 = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)

# Fine-Tune (Stage 2)
base_model.trainable = True

for layer in base_model.layers[:-30]:
    layer.trainable = False

# Recompile with lower LR
model.compile(
    optimizer=Adam(1e-5),
    loss="binary_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.AUC(name="auc"),
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

# Train Stage 2
history2 = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)

# Evaluate
results = model.evaluate(test_ds)
print("Test Results:", results)

# Detailed Metrics
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc

y_true = np.concatenate([y for x, y in test_ds], axis=0).flatten()

y_pred_probs = model.predict(test_ds)

y_pred = (y_pred_probs > 0.5).astype(int).flatten()

# Confusion Matrix

import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np

cm = confusion_matrix(y_true, y_pred)

custom_cmap = mcolors.LinearSegmentedColormap.from_list(
    "real_fake", ["black", "orange"]
)

plt.figure(figsize=(6, 5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap=custom_cmap,
    linewidths=0.5,
    linecolor="gray",
    xticklabels=["FAKE (0)", "REAL (1)"],
    yticklabels=["FAKE (0)", "REAL (1)"],
    annot_kws={"size": 14, "weight": "bold", "color": "white"}
)

plt.xlabel("Predicted Label", fontsize=12)
plt.ylabel("True Label", fontsize=12)
plt.title("Confusion Matrix", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.show()

# Precision, Recall, F1 Score
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

print("\nDetailed Classification Report:\n")
print(classification_report(y_true, y_pred))

# ROC Curve + AUC
fpr, tpr, thresholds = roc_curve(y_true, y_pred_probs)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label="ROC Curve (AUC = %0.4f)" % roc_auc)
plt.plot([0,1], [0,1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

print("AUC Score:", roc_auc)

# Training & Validation Accuracy Curve
acc = history1.history['accuracy'] + history2.history['accuracy']
val_acc = history1.history['val_accuracy'] + history2.history['val_accuracy']

loss = history1.history['loss'] + history2.history['loss']
val_loss = history1.history['val_loss'] + history2.history['val_loss']

# Accuracy Curve
plt.figure(figsize=(6,5))
plt.plot(acc, label='Training Accuracy')
plt.plot(val_acc, label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Training & Validation Accuracy')
plt.legend()
plt.show()

# Loss Curve
plt.figure(figsize=(6,5))
plt.plot(loss, label='Training Loss')
plt.plot(val_loss, label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training & Validation Loss')
plt.legend()
plt.show()